name: Merge Django Apps

on:
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub Actions UI

jobs:
  merge-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EH Repo
        uses: actions/checkout@v3
        with:
          repository: n0tfyet/Nitesh_EH
          path: EH

      - name: Checkout IEC Repo
        uses: actions/checkout@v3
        with:
          repository: n0tfyet/Nitesh_IEC
          path: IEC

      - name: Merge Django Apps
        run: |
          git config --global user.name "n0tfyet"
          git config --global user.email "your_email@example.com"

          mkdir -p temp_merged_apps
          cp -r EH/app/* temp_merged_apps
          find temp_merged_apps -name "*.ipynb" -type f -delete  # Exclude notebooks
          cp -r temp_merged_apps/* IEC/app/
          cd IEC

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Merged Django apps from EH to IEC"
            git push origin main
          else
            echo "No changes to commit"
          fi
          
      - name: Debug File Copy
        run: |
          echo "Files in temp_merged_apps:"
          ls -R temp_merged_apps
          echo "Files in IEC/app:"
          ls -R IEC/app/

      - name: Update General Files
        run: |
          cd IEC
          git remote add EH_remote https://github.com/n0tfyet/Nitesh_EH.git
          git fetch EH_remote main
          git checkout -b temp-merge EH_remote/main
          cp EH/app/settings.py IEC/app
          cp EH/app/urls.py IEC/app
          git checkout main
          git add settings.py urls.py
          git commit -m "Synced general Django files from EH"
          git push origin main
          git branch -D temp-merge
          git remote remove EH_remote
